version: '3.4'

services:
  chenil:
    image: ${DOCKER_REGISTRY-}chenil
    build:
      context: .
      dockerfile: Chenil/Dockerfile
    ports:
    - "8080:80"
    - "10443:443"
    networks:
    - network
  db:
    image: ${DOCKER_REGISTRY-}chenildb
    build:
      context: .
      dockerfile: Chenil/Data/Dockerfile
    environment:
      SA_PASSWORD: "CHANGE_THIS_P4ssW0rd!"
      ACCEPT_EULA: "Y"  
    ports:
    - "1435:1433"
    networks:
    - network
    volumes:
    - database:/var/opt/mssql
networks:
    network:
    
volumes:
    database:
