version: '3.4'

services:
  front:
    image: ${DOCKER_REGISTRY-}front
    build:
      context: .
      dockerfile: Chenil/Front/chenil-front/Dockerfile
      args:
        ANGULAR_ENVIRONMENT: production
    ports:
    - "4202:4200"
    networks:
    - network
  chenil:
    image: ${DOCKER_REGISTRY-}chenil
    build:
      context: .
      dockerfile: Chenil/Dockerfile
    ports:
    - "10443:443"
    networks:
    - network
  db:
    image: ${DOCKER_REGISTRY-}db
    build:
      context: .
      dockerfile: Chenil/Data/Dockerfile
    environment:
      SA_PASSWORD: "CHANGE_THIS_P4ssW0rd!"
      ACCEPT_EULA: "Y"  
    ports:
    - "1435:1433"
    networks:
    - network
    volumes:
    - database:/var/opt/mssql-2
networks:
    network:
    
volumes:
    database:
